name: Heroku Deploy

on:
  push:
    branches:
      - develop
    paths:
      - src/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "counter-assistant-bot"
          heroku_email: "pashagrishyn@gmail.com"
          usedocker: true
          dontuseforce: true
      - run: echo 'Build v. ${{github.ref}}-${{github.sha}} successfully deployed to Heroku'
